### PR TITLE
URL Editor Rewrite

### LINKED ISSUE #60: Fix duplicate HTTP prefix when pasting links
When pasting a URL (that already has the HTTP or HTTPS prefix) into the OONI Run platform, the existing HTTP prefix in the OONI Run URL slot should automatically be removed/deleted to avoid the presence of two HTTP prefixes (and the testing of a broken URL).

### LINKED ISSUE #62: Ensure empty URL slots are not created when copy-pasting URLs
Several community members mentioned that when they copy-paste URLs into the URL slots of OONI Run, empty lines are created between the URLs, which they manually have to delete before clicking the “Generate” button. 

Some community members mentioned that these empty lines usually occur when they copy URLs from a spreadsheet (and there’s an extra space after each URL in the spreadsheet).

### PR DESCRIPTION
**Pull request by sarathms**
This is a rewrite of the URL editor using [`react-hook-form`](react-hook-form.com/).

FIxes #60 
Fixes #62 

* No performance issues even with large number of URLs 
* Improved validation and error messages
* Provides a handy drop down to choose a prefix `https://` or `http://`
image

### CODE REVIEW

**Review by hellais — CHANGES_REQUESTED** [review]
Thanks for putting this together. I have done some testing of the deployed preview.

> Use https as default prefix when adding a URL

This works as expected.

> Avoid duplicating the https prefix when pasting URLs in bulk

I tested this on the deployment preview and it does not work as expected.

When I type into the address bar `https://http`, the string is replaced with `http`. It should rather be replaced with `https://`.

> Add note about ability to paste multiple URLs

OK

**Comment by agrabeli** [comment]
@sarathms @hellais Just sharing a friendly reminder to bump this up in priorities.

**Comment by sarathms** [comment]
Please try the latest preview deployment. This is a rewrite of the URL editor. I have changed the validation strategy to trigger for `onBlur` for the first time and then at every `onChange` event. I feel beginning to validate right after the user starts typing is not a good approach. This is one is a wait-first-then-chase approach.

**Comment by hellais** [comment]
The fact that the validation is only done once you click away from the form creates a UX issues though. It requires that the user clicks outside of the form in order to successfully submit the form. In order to reproduce this, try filling out the first item with a valid URL and notice that the generate button is not clickable. This is quite unexpected.

I would suggest putting the validation logic how it was before. The alternative option would be that we always make the generate button clickable and we trigger the validation logic also when you click on generate and prevent the following screen from appearing unless the form is valid.

**Comment by sarathms** [comment]
> we always make the generate button clickable and we trigger the validation logic also when you click on generate

This seems like a good alternative. I have implemented this in the current deployment.

Also added a static drop down to quickly fill in `https://` and `http://` by clicking in the input field.

**Comment by hellais** [comment]
LGTM

**Pull request merged**
